# coding: utf-8

"""
    Telstra Messaging API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.2.10
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.models.send_sms_multi_request import SendSmsMultiRequest  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestSendSmsMultiRequest(unittest.TestCase):
    """SendSmsMultiRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendSmsMultiRequest(self):
        """Test SendSmsMultiRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Telstra_Messaging.models.send_sms_multi_request.SendSmsMultiRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
