# coding: utf-8

"""
    Telstra Messaging API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.2.10
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.api.authentication_api import AuthenticationApi  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = Telstra_Messaging.api.authentication_api.AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_token(self):
        """Test case for auth_token

        Generate OAuth2 token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
