# coding: utf-8

"""
    Telstra Messaging API

    The Telstra Messaging API specification  # noqa: E501

    The version of the OpenAPI document: 2.2.9
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.models.delete_number_request import DeleteNumberRequest  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestDeleteNumberRequest(unittest.TestCase):
    """DeleteNumberRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteNumberRequest(self):
        """Test DeleteNumberRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Telstra_Messaging.models.delete_number_request.DeleteNumberRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
