# coding: utf-8

"""
    Telstra Messaging API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.2.10
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.models.outbound_poll_response import OutboundPollResponse  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestOutboundPollResponse(unittest.TestCase):
    """OutboundPollResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOutboundPollResponse(self):
        """Test OutboundPollResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Telstra_Messaging.models.outbound_poll_response.OutboundPollResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
