# coding: utf-8

"""
    Telstra Messaging API

     The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages.   # noqa: E501

    OpenAPI spec version: 2.2.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.api.authentication_api import AuthenticationApi  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = Telstra_Messaging.api.authentication_api.AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth_token(self):
        """Test case for auth_token

        Generate authentication token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
