# coding: utf-8

"""
    Telstra Messaging API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.2.10
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.models.provision_number_response import ProvisionNumberResponse  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestProvisionNumberResponse(unittest.TestCase):
    """ProvisionNumberResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProvisionNumberResponse(self):
        """Test ProvisionNumberResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Telstra_Messaging.models.provision_number_response.ProvisionNumberResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
