# coding: utf-8

"""
    Telstra Messaging API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.2.10
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.api.provisioning_api import ProvisioningApi  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestProvisioningApi(unittest.TestCase):
    """ProvisioningApi unit test stubs"""

    def setUp(self):
        self.api = Telstra_Messaging.api.provisioning_api.ProvisioningApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_subscription(self):
        """Test case for create_subscription

        Create Subscription  # noqa: E501
        """
        pass

    def test_delete_subscription(self):
        """Test case for delete_subscription

        Delete Subscription  # noqa: E501
        """
        pass

    def test_get_subscription(self):
        """Test case for get_subscription

        Get Subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
