# coding: utf-8

"""
    Telstra Messaging API

     The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages.   # noqa: E501

    OpenAPI spec version: 2.2.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.models.provision_number_response import ProvisionNumberResponse  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestProvisionNumberResponse(unittest.TestCase):
    """ProvisionNumberResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProvisionNumberResponse(self):
        """Test ProvisionNumberResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Telstra_Messaging.models.provision_number_response.ProvisionNumberResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
