# coding: utf-8

"""
    Telstra Messaging API

     The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages.   # noqa: E501

    OpenAPI spec version: 2.2.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.api.messaging_api import MessagingApi  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestMessagingApi(unittest.TestCase):
    """MessagingApi unit test stubs"""

    def setUp(self):
        self.api = Telstra_Messaging.api.messaging_api.MessagingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_mms_status(self):
        """Test case for get_mms_status

        Get MMS Status  # noqa: E501
        """
        pass

    def test_get_sms_status(self):
        """Test case for get_sms_status

        Get SMS Status  # noqa: E501
        """
        pass

    def test_retrieve_sms_responses(self):
        """Test case for retrieve_sms_responses

        Retrieve SMS Responses  # noqa: E501
        """
        pass

    def test_send_mms(self):
        """Test case for send_mms

        Send MMS  # noqa: E501
        """
        pass

    def test_send_sms(self):
        """Test case for send_sms

        Send SMS  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
