# coding: utf-8

"""
    Telstra Messaging API

    The API specification for Telstra Messaging API  # noqa: E501

    The version of the OpenAPI document: 2.2.9
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.models.get_subscription_response import GetSubscriptionResponse  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestGetSubscriptionResponse(unittest.TestCase):
    """GetSubscriptionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSubscriptionResponse(self):
        """Test GetSubscriptionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Telstra_Messaging.models.get_subscription_response.GetSubscriptionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
