# coding: utf-8

"""
    Telstra Messaging API

     The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages.   # noqa: E501

    OpenAPI spec version: 2.2.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.api.auth_api import AuthApi  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self):
        self.api = Telstra_Messaging.api.auth_api.AuthApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_oauth_token_post(self):
        """Test case for oauth_token_post

        AuthGeneratetokenPost  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
