# coding: utf-8

"""
    Telstra Messaging API

    The Telstra Messaging API specification  # noqa: E501

    The version of the OpenAPI document: 2.2.9
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import Telstra_Messaging
from Telstra_Messaging.models.inbound_poll_response import InboundPollResponse  # noqa: E501
from Telstra_Messaging.rest import ApiException


class TestInboundPollResponse(unittest.TestCase):
    """InboundPollResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInboundPollResponse(self):
        """Test InboundPollResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Telstra_Messaging.models.inbound_poll_response.InboundPollResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
