# coding: utf-8

"""
    Telstra Messaging API

    The Telstra Messaging API specification  # noqa: E501

    The version of the OpenAPI document: 2.2.9
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from Telstra_Messaging.configuration import Configuration


class ProvisionNumberRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'active_days': 'int',
        'notify_url': 'str'
    }

    attribute_map = {
        'active_days': 'activeDays',
        'notify_url': 'notifyURL'
    }

    def __init__(self, active_days=None, notify_url=None, local_vars_configuration=None):  # noqa: E501
        """ProvisionNumberRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._active_days = None
        self._notify_url = None
        self.discriminator = None

        if active_days is not None:
            self.active_days = active_days
        if notify_url is not None:
            self.notify_url = notify_url

    @property
    def active_days(self):
        """Gets the active_days of this ProvisionNumberRequest.  # noqa: E501

        The number of days before for which this number is provisioned.   # noqa: E501

        :return: The active_days of this ProvisionNumberRequest.  # noqa: E501
        :rtype: int
        """
        return self._active_days

    @active_days.setter
    def active_days(self, active_days):
        """Sets the active_days of this ProvisionNumberRequest.

        The number of days before for which this number is provisioned.   # noqa: E501

        :param active_days: The active_days of this ProvisionNumberRequest.  # noqa: E501
        :type: int
        """

        self._active_days = active_days

    @property
    def notify_url(self):
        """Gets the notify_url of this ProvisionNumberRequest.  # noqa: E501

        A notification URL that will be POSTed to whenever a new message (i.e. a reply to a message sent) arrives at this destination address.  If this is not provided then you can use the Get /sms or /mms API to poll for reply messages.  If you are using a domain URL you must include the forward slash at the end of the URL (e.g. http://www.example.com/).  *Please note that the notification URLs and the Get /sms or /mms call are exclusive. If a notification URL has been set then the GET call will not provide any useful information.*   # noqa: E501

        :return: The notify_url of this ProvisionNumberRequest.  # noqa: E501
        :rtype: str
        """
        return self._notify_url

    @notify_url.setter
    def notify_url(self, notify_url):
        """Sets the notify_url of this ProvisionNumberRequest.

        A notification URL that will be POSTed to whenever a new message (i.e. a reply to a message sent) arrives at this destination address.  If this is not provided then you can use the Get /sms or /mms API to poll for reply messages.  If you are using a domain URL you must include the forward slash at the end of the URL (e.g. http://www.example.com/).  *Please note that the notification URLs and the Get /sms or /mms call are exclusive. If a notification URL has been set then the GET call will not provide any useful information.*   # noqa: E501

        :param notify_url: The notify_url of this ProvisionNumberRequest.  # noqa: E501
        :type: str
        """

        self._notify_url = notify_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProvisionNumberRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProvisionNumberRequest):
            return True

        return self.to_dict() != other.to_dict()
